name: Dagifier
repo: Dagifier
owner: anton
archetype: cli
template_ref: cli_app:0.1.0
contract_version: 1.0.0
lifecycle_state: active_dev
visibility: private
domain: terminal
description: High-performance content extraction and ASCII rendering engine.
commands:
  deps: npm install
  build: npm run build
  test: npm test
  run: npm start
  check: npm run build && npm test
version: 2
